version: '3.1'
volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local
services:
  tests:
    user: '$UID:0'
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    volumes:
      - .:/app
      - app-gems:/app/vendor/bundle
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:suppa-duppa@postgres:5432/test_database
  postgres:
    image: 'postgres:14.2-alpine'
    environment:
      POSTGRES_PASSWORD: suppa-duppa
    volumes:
      - postgres-data:/var/lib/postgresql/data